/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gaort
 */
public class Interfaz extends javax.swing.JFrame {
    //Matrices utilizadas para los animales, habitats y visitantes
    public static Animal[] arrAnimal = new Animal[100];
    
    public static Habitat[] arrHabitat = new Habitat[100];
    
    public static Alimetos[] arrAli = new Alimetos[100];
    
   
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        PrecargadaA(arrAnimal);
        PrecargadaH(arrHabitat);
        PrecargadaAL(arrAli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPsw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        IngresarContra = new javax.swing.JPasswordField();
        BotonIngresar = new java.awt.Button();
        IngresarNombreU1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/undefined_image.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 680));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setDisplayedMnemonic('I');
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Iniciar Sesión");
        jLabel3.setToolTipText("Iniciar sesión");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 320, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        txtPsw.setBackground(new java.awt.Color(255, 255, 255));
        txtPsw.setForeground(new java.awt.Color(51, 51, 51));
        txtPsw.setBorder(null);
        txtPsw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPswMousePressed(evt);
            }
        });
        txtPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswActionPerformed(evt);
            }
        });
        jPanel2.add(txtPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 310, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 320, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 320, 20));

        IngresarContra.setBackground(new java.awt.Color(255, 255, 255));
        IngresarContra.setForeground(new java.awt.Color(51, 51, 51));
        IngresarContra.setBorder(null);
        IngresarContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarContraMousePressed(evt);
            }
        });
        IngresarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarContraActionPerformed(evt);
            }
        });
        jPanel2.add(IngresarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        BotonIngresar.setActionCommand("Ingresar");
        BotonIngresar.setBackground(new java.awt.Color(0, 204, 51));
        BotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIngresar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        BotonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BotonIngresar.setLabel("Ingresar");
        BotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonIngresarMouseEntered(evt);
            }
        });
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 130, 60));

        IngresarNombreU1.setBackground(new java.awt.Color(255, 255, 255));
        IngresarNombreU1.setForeground(new java.awt.Color(51, 51, 51));
        IngresarNombreU1.setBorder(null);
        IngresarNombreU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarNombreU1MousePressed(evt);
            }
        });
        IngresarNombreU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreU1ActionPerformed(evt);
            }
        });
        jPanel2.add(IngresarNombreU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIngresarMouseEntered

    }//GEN-LAST:event_BotonIngresarMouseEntered

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        String user = IngresarNombreU1.getText();
        String psw = txtPsw.getText();

        if (user.equals("Admin") && psw.equals("1234")) {
            Ventana1 ventana1 = new Ventana1();
            ventana1.setVisible(true);
            this.setVisible(false);
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Usuario y Contraseña incorrecta");
        }


    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void txtPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswActionPerformed


    }//GEN-LAST:event_txtPswActionPerformed

    private void txtPswMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPswMousePressed
        if (txtPsw.getText().equals("Ingrese su nombre de usuario")) {
            txtPsw.setText("");
            txtPsw.setForeground(Color.black);
        }
        if (String.valueOf(IngresarContra.getPassword()).isEmpty()) {
            IngresarContra.setText("********");
            IngresarContra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPswMousePressed

    private void IngresarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarContraActionPerformed

    }//GEN-LAST:event_IngresarContraActionPerformed

    private void IngresarContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarContraMousePressed
        if (String.valueOf(IngresarContra.getPassword()).equals("********")) {
            IngresarContra.setText("");
            IngresarContra.setForeground(Color.black);
        }
        if (txtPsw.getText().isEmpty()) {
            txtPsw.setText("Ingrese su nombre de usuario");
            txtPsw.setForeground(Color.gray);
        }
    }//GEN-LAST:event_IngresarContraMousePressed

    private void IngresarNombreU1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarNombreU1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNombreU1MousePressed

    private void IngresarNombreU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreU1ActionPerformed

    }//GEN-LAST:event_IngresarNombreU1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //datos precargados en matriz unicamente para ellos
        Object[][] arrAnimales = new Object[100][4];

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    public void PrecargadaA(Animal[] info) {
        this.arrAnimal[0] = new Animal("Oso", "Oso polar", 2, "Artico" );
        
        this.arrAnimal[1] = new Animal("Puma", "Concolor", 1, "Sabana");
        
        this.arrAnimal[2] = new Animal("Leon", "Panthera", 3, "Bosque");
        
        this.arrAnimal[3] = new Animal("Lemur", "Raton gris", 4, "Bosque");
        
        
    }
    //Informacion precargada
    public void PrecargadaH(Habitat[] info) {
        this.arrHabitat[0] = new Habitat("Desierto", "Caluroso", 54);
        
        this.arrHabitat[1] = new Habitat("Bosque", "Humedo", 32);
        
        this.arrHabitat[2] = new Habitat("Artico", "frio", 27);
        
        this.arrHabitat[3] = new Habitat("Sabana", "Calido", 40);
    }
    
    public void PrecargadaAL(Alimetos[] info) {
        this.arrAli[0] = new Alimetos("Oso", "3 pm", "carne", "3 veces al dia");
        
        this.arrAli[1] = new Alimetos("Puma", "6 am", "Pollo", "6 veces al dia");
        
        this.arrAli[2] = new Alimetos("Leon", "2 pm", "carnes rojas", "9 veces al dia");
        
        this.arrAli[3] = new Alimetos("Lemur", "12 am", "hojas", "2 veces al dia");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BotonIngresar;
    private javax.swing.JPasswordField IngresarContra;
    private javax.swing.JTextField IngresarNombreU1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtPsw;
    // End of variables declaration//GEN-END:variables
}
