/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author gaort
 */
public class RegistroEventos extends javax.swing.JFrame {

    private int contador = 0;
    private String[] nombres = new String[100];
    private String[] fechas = new String[100];
    private int[] ids = new int[100];
    private String[] descri = new String[100];

    /**
     * Creates new form RegistroEventos
     */
    public RegistroEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombretxt = new javax.swing.JLabel();
        fechatxt = new javax.swing.JLabel();
        idtxt = new javax.swing.JLabel();
        descriptxt = new javax.swing.JLabel();
        RegistrarEvento = new javax.swing.JButton();
        Cinfo = new javax.swing.JButton();
        fEventostxt = new javax.swing.JTextField();
        idEventostxt = new javax.swing.JTextField();
        dEventostxt = new javax.swing.JTextField();
        nEventostxt = new javax.swing.JTextField();
        BInfo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Registro De Eventos");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nombretxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(204, 255, 204));
        nombretxt.setText("Nombre");

        fechatxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        fechatxt.setForeground(new java.awt.Color(204, 255, 204));
        fechatxt.setText("Fecha (dd/mm/yyyy)");

        idtxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        idtxt.setForeground(new java.awt.Color(204, 255, 204));
        idtxt.setText("ID");

        descriptxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        descriptxt.setForeground(new java.awt.Color(204, 255, 204));
        descriptxt.setText("Descripción del evento");

        RegistrarEvento.setBackground(new java.awt.Color(255, 255, 153));
        RegistrarEvento.setText("Registrar Evento");
        RegistrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEventoActionPerformed(evt);
            }
        });

        Cinfo.setBackground(new java.awt.Color(255, 255, 153));
        Cinfo.setText("Consultar información");
        Cinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinfoActionPerformed(evt);
            }
        });

        fEventostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fEventostxtActionPerformed(evt);
            }
        });

        BInfo.setBackground(new java.awt.Color(255, 255, 153));
        BInfo.setText("Buscar información");
        BInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInfoActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setText("Eliminar información");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setText("Modificar información");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dEventostxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nEventostxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fEventostxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEventostxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(329, 329, 329)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(descriptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RegistrarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(Cinfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jButton6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(nombretxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nEventostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechatxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fEventostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idtxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idEventostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dEventostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ventana1 ventana = new Ventana1();

        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEventoActionPerformed
        String nombre = nEventostxt.getText();
        String fecha = fEventostxt.getText();
        String id = idEventostxt.getText();
        String descrip = dEventostxt.getText();
        if (nombre.isEmpty() || fecha.isEmpty() || id.isEmpty() || descrip.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error, complete todos los campos ");
        } else if (ent(id) && str(nombre) && fecha(fecha) && str(descrip)) {

            int idInt = Integer.parseInt(id);

            if (contador < nombres.length) {
                nombres[contador] = nombre;
                fechas[contador] = fecha;
                ids[contador] = idInt;
                descri[contador] = descrip;

                contador++;

                nEventostxt.setText("");
                fEventostxt.setText("");
                idEventostxt.setText("");
                dEventostxt.setText("");

                JOptionPane.showMessageDialog(null, "Datos guardados correctamente ");
            } else {
                JOptionPane.showMessageDialog(null, "Error, no se permiten los datos ingresados ");
            }
        }
    }

    private void imprimir() {
        if (contador == 0) {
            JOptionPane.showMessageDialog(null, "No hay eventos en el registro ");
        } else {
            String mensaje = "";
            for (int i = 0; i < contador; i++) {
                mensaje += "Evento: " + (i + 1) + ":\n";
                mensaje += "Nombre del evento: " + nombres[i] + "\n";
                mensaje += "Fecha del evento: " + fechas[i] + "\n";
                mensaje += "Id del evento: " + ids[i] + "\n";
                mensaje += "Descripcion del evento: " + descri[i] + "\n";
                mensaje += ("\n");
            }
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }

    private void buscarEvento(String nombre) {
        boolean encontrado = false;

        for (int i = 0; i < contador; i++) {
            if (nombres[i].equalsIgnoreCase(nombre)) {
                JOptionPane.showMessageDialog(null, "Evento encontrado \nNombre: " + nombres[i]
                        + "\nfecha: " + fechas[i]
                        + "\nid: " + ids[i]
                        + "\nDescripcion: " + descri[i]);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Evento no encontrado.");
        }
    }

    private void eliminarEvento(String nombre) {
        boolean encontrado = false;

        for (int i = 0; i < contador; i++) {
            if (nombres[i].equalsIgnoreCase(nombre)) {
                for (int j = i; j < contador - 1; j++) {
                    nombres[j] = nombres[j + 1];
                    fechas[j] = fechas[j + 1];
                    ids[j] = ids[j + 1];
                    descri[j] = descri[j + 1];
                }
                contador--;
                encontrado = true;
                JOptionPane.showMessageDialog(null, "Evento eliminado correctamente.");
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Evento no encontrado.");
        }
    }

    private boolean str(String valor) {
        return valor.matches("[a-zA-Z ]+");
    }

    private boolean fecha(String fecha) {
        return fecha.matches("\\d{2}/\\d{2}/\\d{4}");
    }

    private boolean ent(String valor) {
        if (valor.matches("\\d+")) {
            return true;
        } else {
            return false;
        }


    }//GEN-LAST:event_RegistrarEventoActionPerformed

    private void CinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CinfoActionPerformed
        imprimir();
    }//GEN-LAST:event_CinfoActionPerformed

    private void fEventostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEventostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fEventostxtActionPerformed

    private void BInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInfoActionPerformed
        String buscar = JOptionPane.showInputDialog(null, "Ingrese el nombre del evento que quiera eliminar");
        buscarEvento(buscar);
    }//GEN-LAST:event_BInfoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String eliminar = JOptionPane.showInputDialog(null, "Ingrese el nombre del evento que quiera eliminar");
        eliminarEvento(eliminar);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Evento evento = new Evento();
        evento.opcion();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInfo;
    private javax.swing.JButton Cinfo;
    private javax.swing.JButton RegistrarEvento;
    private javax.swing.JTextField dEventostxt;
    private javax.swing.JLabel descriptxt;
    private javax.swing.JTextField fEventostxt;
    private javax.swing.JLabel fechatxt;
    private javax.swing.JTextField idEventostxt;
    private javax.swing.JLabel idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nEventostxt;
    private javax.swing.JLabel nombretxt;
    // End of variables declaration//GEN-END:variables
}
